server:
  port: 0


spring:

  application:
    name: credit-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/credit-db



eureka:

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true